import type {
	CHANNEL_CATEGORIES,
	CONVERSATION_CHANNELS,
	LANDING_MEDIUMS,
	MESSAGE_ISSUE_SOURCES,
	MOBILE_CHANNELS,
	OPPORTUNITY_STATUSES,
	REQUIREMENT_GROUPS,
	REQUIREMENT_TYPES,
	TALENT_ACTIVITY_PROVIDERS,
} from "./schemas.ts";

export enum Provider {
	EMAIL = "email",
	LINKEDIN = "linkedin",
	IMESSAGE = "imessage",
	WHATSAPP = "whatsapp",
	SMS = "sms",
	SLACK = "slack",
	API = "api",
	AGENT = "agent",
	MOBILE = "mobile",
	SYSTEM = "system",
}

export enum CommunicationChannel {
	INSTANTLY = "instantly",
	LINKEDIN = "linkedin",
	BREVO = "brevo",
	MCP = "mcp",
	MOBILE = "mobile",
}

export enum OpportunityEventType {
	talent_calibrated = "talent_calibrated",
	talent_submitted = "talent_submitted",
	company_reacted = "company_reacted",
	make_intro = "make_intro",
	interview_invited = "interview_invited",
	interview_accepted = "interview_accepted",
	interview_declined = "interview_declined",
	interview_scheduled = "interview_scheduled",
	interview_rescheduled = "interview_rescheduled",
	interview_reminded = "interview_reminded",
	interview_canceled = "interview_canceled",
	interview_completed = "interview_completed",
	hiring_manager_no_show = "hiring_manager_no_show",
	clera_team_no_show = "clera_team_no_show",
	interview_context_updated = "interview_context_updated",
	talent_withdrawn = "talent_withdrawn",
	talent_rejected = "talent_rejected",
	talent_placed = "talent_placed",
	general_update = "general_update",
	question_asked = "question_asked",
	offer_extended = "offer_extended",
	offer_accepted = "offer_accepted",
	offer_declined = "offer_declined",
}

export enum OpportunityActivitySource {
	talent = "talent",
	company = "company",
	internal = "internal",
}

export enum AutoReplyClassifications {
	welcome_reply = "welcome_reply",
	negative_intent = "negative_intent",
	should_send_opportunity_link = "should_send_opportunity_link",
	agent_should_handle_it = "agent_should_handle_it",
	privacy_concern_detected = "privacy_concern_detected",
}

export enum TalentTags {
	no_human_touchpoint = "no_human_touchpoint",
	automation_disclosure = "automation_disclosure",
	automation_no_disclosure = "automation_no_disclosure",
}

export enum SlackChannel {
	mobile_comms = "mobile-comms",
	mobile_comms_company = "mobile-comms-company",
	new_talents = "new-talents",
	recruiter_opportunities = "recruiter-opportunities",
	new_company_activity = "8-new-company-activity",
	company_signups = "8-company-signups",
	new_chat_started = "new-chat-started",
	role_assignment_issue = "role-assignment-issue",
	new_roles = "new-roles",
	auto_replies = "auto-replies",
	unipile_account_status_update = "unipile-account-status-update",
	client_acquisition = "client-acquisition",
	email_health_check = "9-email-health-check",
	instantly_unread_count = "9-instantly-unread",
	talent_submissions = "talent-submissions",
	client_calibrations = "client-calibrations",
	external_calibrations = "external-calibrations",
	data_reports = "data-reports",
	fuckup_reports = "9-fuckup-reports",
	tone_of_voice_fuckups = "tone-of-voice-fuckups",
	matchmaking_feedback = "matchmaking-feedback",
	agent_bug_reports = "9-agent-bug-reports",
	duplicate_talent_channels = "9-duplicate-talent-channels",
	summon_engineering = "9-summon-engineering",
	system_guard_alerts = "9-system-guard-alerts",
	paraform_bot_logs = "9-paraform-bot-logs",
	paraform_job_import_channel_id = "C0BH4FZNV9R",
	agent_improvements = "9-agent-improvements",
	product_notifications = "product-notifications",
	sourcing_campaigns = "sourcing-campaigns",
	intercom = "intercom-support",
	experience_fuckups = "experience-fuckups",
	talent_team = "talent-team",
	summon_talent_team = "9-summon-talent-team",
	fake_profile_verdicts = "9-fake-profile-verdicts",
	summon_client_team = "8-summon-client-team",
	recruiter_analytics_logins = "recruiter_analytics_logins",
	company_analytics_logins = "company_analytics_logins",
	submission_drops_added = "tt-submission-drops-added",
	elo_feedback = "C0BJF79U4F9",
	org_feedback = "9-org-feedback",
	seo_alerts = "9-seo-alerts",
	company_request_issues = "9-company-request-issues",
	hm_link_missing_clera = "9-hm-link-missing-clera",
	partner_submit_ready = "9-paraform-submit-ready",
	talent_team_analytics = "C0B7L6RND9U",
	auto_submission_overflow = "C0AN847VBFD",
	shipped = "shipped",
	drops_ops = "drops-ops",
	gabana_monitoring = "9-gabana-monitoring",
	tech = "tech",
	felix_dm = "U0BE2V7DVJQ",
}

export enum SlackMessageType {
	new_chat_started = "new_chat_started",
	opportunity_questions_answered = "opportunity_questions_answered",
	opportunity_interest = "opportunity_interest",
	new_waitlist_signup = "new_waitlist_signup",
	new_user_registration = "new_user_registration",
	new_job_application = "new_job_application",
	role_assignment_issue = "role_assignment_issue",
	role_assignment_issue_list = "role_assignment_issue_list",
	new_paraform_jobs = "new_paraform_jobs",
	role_questions_reminder = "role_questions_reminder",
	missing_description_reminder = "missing_description_reminder",
	automatic_opps_link_sent = "automatic_opps_link_sent",
	bulk_opportunity_interest = "bulk_opportunity_interest",
	bulk_opportunity_questions_answered = "bulk_opportunity_questions_answered",
	unverified_opportunities_report = "unverified_opportunities_report",
	unipile_account_status_update = "unipile_account_status_update",
	company_waitlist_signup = "company_waitlist_signup",
	cleramap_submission = "cleramap_submission",
	integration_request = "integration_request",
	email_health_report = "email_health_report",
	maracuja_health_report = "maracuja_health_report",
	blog_content_qa_report = "blog_content_qa_report",
	talent_state_ops_report = "talent_state_ops_report",
	ats_board_new_postings = "ats_board_new_postings",
	instantly_unread_count = "instantly_unread_count",
	partner_notification = "partner_notification",
	talent_marked_unfit = "talent_marked_unfit",
	talent_moved_backlog = "talent_moved_backlog",
	cv_uploaded = "cv_uploaded",
	new_talent_by_recruiter = "new_talent_by_recruiter",
	opportunity_by_recruiter = "opportunity_by_recruiter",
	resubmission_reminders_1 = "resubmission_reminder_1",
	resubmission_reminders_2 = "resubmission_reminder_2",
	resubmission_reminders_3 = "resubmission_reminder_3",
	calibration_reminders_3 = "calibration_reminder_3",
	new_interview = "new_interview",
	new_submission = "new_submission",
	talent_placed = "talent_placed",
	clera_calibration_notification = "clera_calibration_notification",
	external_calibration_notification = "external_calibration_notification",
	daily_submission_summary = "daily_submission_summary",
	weekly_submission_summary = "weekly_submission_summary",
	weekly_issue_report = "weekly_issue_report",
	job_data_health_report = "job_data_health_report",
	job_missing_location = "job_missing_location",
	mobile_chat_started = "mobile_chat_started",
	mobile_error = "mobile_error",
	mobile_health_check = "mobile_health_check",
	mobile_conversation_summary = "mobile_conversation_summary",
	mobile_company_chat_started = "mobile_company_chat_started",
	mobile_company_error = "mobile_company_error",
	mobile_company_health_check = "mobile_company_health_check",
	mobile_company_conversation_summary = "mobile_company_conversation_summary",
	phone_number_added = "phone_number_added",
	message_fuckup = "message_fuckup",
	message_fuckup_tone = "message_fuckup_tone",
	opportunity_is_submittable = "opportunity_is_submittable",
	company_facilitate_intro = "company_facilitate_intro",
	company_email_reply = "company_email_reply",
	company_pass = "company_pass",
	company_request_intro = "company_request_intro",
	company_request_submit_ready = "company_request_submit_ready",
	company_awaiting_approval = "company_awaiting_approval",
	company_ats_integration_requested = "company_ats_integration_requested",
	company_created_role = "company_created_role",
	company_paused_role = "company_paused_role",
	company_closed_role = "company_closed_role",
	company_reopened_role = "company_reopened_role",
	company_imported_by_admin = "company_imported_by_admin",
	company_signed_up = "company_signed_up",
	worth_calculation_completed = "worth_calculation_completed",
	resume_review_completed = "resume_review_completed",
	duplicate_talent_channel = "duplicate_talent_channel",
	talent_auto_merged = "talent_auto_merged",
	summon_engineering = "summon_engineering",
	summon_talent_team = "summon_talent_team",
	summon_client_team = "summon_client_team",
	e2e_site_health = "e2e_site_health",
	daily_timeout_report = "daily_timeout_report",
	daily_shipped_digest = "daily_shipped_digest",
	unreviewed_submittable_report = "unreviewed_submittable_report",
	submittability_accuracy_report = "submittability_accuracy_report",
	submittability_weekly_report = "submittability_weekly_report",
	never_submit_guard_alert = "never_submit_guard_alert",
	warning_indicators_alert = "warning_indicators_alert",
	talent_experience_analysis_report = "talent_experience_analysis_report",
	mobile_onboarding_report = "mobile_onboarding_report",
	request_delete = "request_delete",
	potential_delete_request = "potential_delete_request",
	experience_feedback = "experience_feedback",
	new_block_application = "new_block_application",
	daily_submission_ranking = "daily_submission_ranking",
	agent_blocked_opportunity = "agent_blocked_opportunity",
	pipeline_health_check = "pipeline_health_check",
	web_talent_chat_started = "web_talent_chat_started",
	web_company_chat_started = "web_company_chat_started",
	sixtyfour_campaign_created = "sixtyfour_campaign_created",
	stale_submittable_cleanup = "stale_submittable_cleanup",
	paused_role_opportunity_sync = "paused_role_opportunity_sync",
	sourcing_escalation_request = "sourcing_escalation_request",
	recruiting_partner_submission = "recruiting_partner_submission",
	talent_wants_to_hire = "talent_wants_to_hire",
	recruiter_login = "recruiter_login",
	company_login = "company_login",
	tam_draft_batch_complete = "tam_draft_batch_complete",
	talent_finder_dealbreaker_taste_conflict = "talent_finder_dealbreaker_taste_conflict",
	new_funding_signals = "new_funding_signals",
	elo_score_feedback = "elo_score_feedback",
	org_feedback = "org_feedback",
	layoff_campaign_processed = "layoff_campaign_processed",
	layoff_outreach_backlog = "layoff_outreach_backlog",
	pool_talent_added = "pool_talent_added",
	seo_alert = "seo_alert",
	user_reported_pseo_job = "user_reported_pseo_job",
	integration_credits_report = "integration_credits_report",
	fake_profile_auto_closed = "fake_profile_auto_closed",
	resume_builder_used = "resume_builder_used",
	instantly_scheduled_leads_report = "instantly_scheduled_leads_report",
	booking_proxy_failure = "booking_proxy_failure",
	intro_email_failure = "intro_email_failure",
	gabana_unlinked_channel = "gabana_unlinked_channel",
	hm_link_missing_clera = "hm_link_missing_clera",
	partner_submit_ready = "partner_submit_ready",
	email_verification_deferred_alert = "email_verification_deferred_alert",
	paraform_job_import_failure = "paraform_job_import_failure",
	paraform_job_import_report = "paraform_job_import_report",
	paraform_scrape_failure = "paraform_scrape_failure",
	paraform_scrape_report = "paraform_scrape_report",
	paraform_seat_ledger_report = "paraform_seat_ledger_report",
	paraform_request_conversion_report = "paraform_request_conversion_report",
	placeholder_mart_missing = "placeholder_mart_missing",
	drop_unlocked = "drop_unlocked",
	talent_connections_uploaded = "talent_connections_uploaded",
	demo_email_captured = "demo_email_captured",
	client_joined_slack_channel = "client_joined_slack_channel",
	aimfox_flowless_campaigns_alert = "aimfox_flowless_campaigns_alert",
	outbox_queue_alert = "outbox_queue_alert",
	match_link_opened_empty = "match_link_opened_empty",
	paused_queues_alert = "paused_queues_alert",
	partner_mail_classifier_alert = "partner_mail_classifier_alert",
	job_data_quality_alert = "job_data_quality_alert",
	stale_pull_requests_closed = "stale_pull_requests_closed",
	recall_bot_dispatch_failure = "recall_bot_dispatch_failure",
	recall_recording_no_audio = "recall_recording_no_audio",
	calendar_account_disconnected = "calendar_account_disconnected",
	calibration_slack_delete_failure = "calibration_slack_delete_failure",
	drop_no_response_digest = "drop_no_response_digest",
	drop_second_list_no_response = "drop_second_list_no_response",
	role_zero_engagement_close = "role_zero_engagement_close",
	jobs_missing_requirements = "jobs_missing_requirements",
	gabana_sensitive_action = "gabana_sensitive_action",
	gabana_replay_digest = "gabana_replay_digest",
	privacy_request_received = "privacy_request_received",
	privacy_fanout_failed = "privacy_fanout_failed",
	mcp_tool_error = "mcp_tool_error",
}

export enum EmailMessageType {
	org_intro_request_confirmation = "org_intro_request_confirmation",
	admin_fup_reminder = "admin_fup_reminder",
	admin_comment_notification = "admin_comment_notification",
	recruiter_comment_reminder = "recruiter_comment_reminder",
	new_opportunities_notification = "new_opportunities_notification",
	waitlist_notification = "waitlist_notification",
	recruiter_comment_notification = "recruiter_comment_notification",
	new_talent_by_recruiter = "new_talent_by_recruiter",
	recruiter_bulk_import = "recruiter_bulk_import",
	new_talent_analysis_feedback = "new_talent_analysis_feedback",
	talent_reaction_check = "talent_reaction_check",
	talent_opportunity_link_fup = "talent_opportunity_link_fup",
	talent_no_interest_fup = "talent_no_interest_fup",
	talent_no_interest_fup_1 = "talent_no_interest_fup_1",
	talent_no_interest_fup_2 = "talent_no_interest_fup_2",
	talent_opportunity_link_fup_1 = "talent_opportunity_link_fup_1",
	talent_opportunity_link_fup_2 = "talent_opportunity_link_fup_2",
	talent_opportunity_link_fup_3 = "talent_opportunity_link_fup_3",
	talent_questions_fup = "talent_questions_fup",
	talent_questions_fup_1 = "talent_questions_fup_1",
	talent_questions_fup_2 = "talent_questions_fup_2",
	talent_questions_fup_3 = "talent_questions_fup_3",
	talent_welcome = "talent_welcome",
	recruiter_welcome = "recruiter_welcome",
	new_opportunity_matches_fup = "new_opportunity_matches_fup",
	job_search_complete = "job_search_complete",
	message_sent = "message_sent",
	message_received = "message_received",
	no_interest_acknowledgement = "no_interest_acknowledgement",
	opportunities_link_auto = "opportunities_link_auto",
	manual_brevo_message = "manual_brevo_message",
	org_intro_digest = "org_intro_digest",
	org_drops_ready = "org_calibration_ready",
	org_stale_intro_reminder = "org_stale_intro_reminder",
	org_weekly_digest = "org_weekly_digest",
	self_service_company_claim = "self_service_company_claim",
	integration_request_confirmation = "integration_request_confirmation",
	org_ats_roles_ready = "org_ats_roles_ready",
}

export enum AutomatedMessageType {
	submission_confirmation = "submission_confirmation",
	submission_marked_unfit = "submission_marked_unfit",
	linkedin_signup = "linkedin_signup",
	email_signup = "email_signup",
	talent_signup = "talent_signup",
	role_emails_opted_in = "role_emails_opted_in",
	new_referral_added = "new_referral_added",
	request_job_refinement = "request_job_refinement",
	completed_interview = "completed_interview",
	completed_interview_rejection = "completed_interview_rejection",
	request_for_minimal_information = "request_for_minimal_information",
	check_in_after_signing = "check_in_after_signing",
	check_in_after_signing_3_months = "check_in_after_signing_3_months",
	preferences_updated = "preferences_updated",
	offer_negotiation_reminder = "offer_negotiation_reminder",
	offer_rejection_notification = "offer_rejection_notification",
	schedule_interview_reminder = "schedule_interview_reminder",
	dormant_3_months_follow_up = "dormant_3_months_fup_1",
	reengagement_tenure_2y = "reengagement_tenure_2y",
	reengagement_tenure_4y = "reengagement_tenure_4y",
	message_fuckup = "message_fuckup",
	linkedin_connection_webhook = "linkedin_connection_webhook",
	linkedin_connection_outreach = "linkedin_connection_outreach",
	aimfox_campaign_message = "aimfox_campaign_message",
	linkedin_account_handoff_invite = "linkedin_account_handoff_invite",
	admin_manual_fup = "admin_manual_fup",
	should_send_interview_prep = "should_send_interview_prep",
	no_opps_found_no_auto_reply = "no_opps_found_no_auto_reply",
	no_opps_found_need_human_check = "no_opps_found_need_human_check",
	no_opps_reassurance = "no_opps_reassurance",
	low_elo_no_matches = "low_elo_no_matches",
	included_mobile_cta = "included_mobile_cta",
	job_application_welcome = "job_application_welcome",
	job_application_submitted = "job_application_submitted",
	blind_application_welcome = "blind_application_welcome",
	blind_application_intro_offer = "blind_application_intro_offer",
	blind_application_decline = "blind_application_decline",
	blind_application_follow_up = "blind_application_fup_1",
	blind_application_repeat_ping = "blind_application_repeat_ping",
	blind_application_acknowledgment = "blind_application_acknowledgment",
	blind_application_subsequent = "blind_application_subsequent",
	blind_application_role_declined = "blind_application_role_declined",
	blind_application_gentle_close = "blind_application_gentle_close",
	blind_application_v2_welcome = "blind_application_v2_welcome",
	blind_application_v2_confirmation = "blind_application_v2_confirmation",
	blind_application_v2_eval_outcome = "blind_application_v2_eval_outcome",
	blind_application_v2_eval_conversational = "blind_application_v2_eval_conversational",
	cohort_application_welcome = "cohort_application_welcome",
	whatsapp_company_agent = "whatsapp_company_agent",
	linkedin_connection_accepted = "linkedin_connection_accepted",
	should_ask_estimated_date_confirmation = "should_ask_estimated_date_confirmation",
	should_submit_for_paraform_role = "should_submit_for_paraform_role",
}

export const BLIND_JOB_MARKER_EVENT_TYPES: AutomatedMessageType[] = [
	AutomatedMessageType.blind_application_welcome,
	AutomatedMessageType.blind_application_intro_offer,
	AutomatedMessageType.blind_application_repeat_ping,
	AutomatedMessageType.blind_application_acknowledgment,
	AutomatedMessageType.blind_application_decline,
	AutomatedMessageType.blind_application_subsequent,
	AutomatedMessageType.blind_application_role_declined,
];

export enum AgentType {
	referral_detected = "referral_detected",
	agent_followup_sent_message_1 = "agent_followup_sent_message_1",
	summon_talent_team = "summon_talent_team",
	request_delete = "request_delete",
	blacklist_talent = "blacklist_talent",
	talent_hired = "talent_hired",
	talent_barred = "talent_barred",
	talent_marked_fake = "talent_marked_fake",
	authenticity_evaluated = "authenticity_evaluated",
	consent_revoked = "consent_revoked",
	erasure_requested = "erasure_requested",
	privacy_access_requested = "privacy_access_requested",
	privacy_request_evaluated = "privacy_request_evaluated",
	subject_reengaged = "subject_reengaged",
	summon_engineering = "summon_engineering",
	request_call = "request_call",
	agent_scheduled_reminder = "agent_scheduled_reminder",
	agent_reminder_fired = "agent_reminder_fired",
	agent_trigger_issue = "agent_trigger_issue",
	agent_reminder_executed = "agent_reminder_executed",
	agent_reminder_cancelled = "agent_reminder_cancelled",
	agent_reminder_dropped = "agent_reminder_dropped",
	agent_activity_dropped = "agent_activity_dropped",
	agent_check_in = "agent_check_in",
	system_fup_bundle_due = "system_fup_bundle_due",
	agent_check_in_dropped = "agent_check_in_dropped",
	leo_agent = "leo_agent",
	leo_agent_summoned_cleon = "leo_agent_summoned_cleon",
	leo_send_opportunity_link = "leo_send_opportunity_link",
	send_opportunity_link = "send_opportunity_link",
	leo_email_signup_welcome = "leo_email_signup_welcome",
	leo_linkedin_signup_welcome = "leo_linkedin_signup_welcome",
	leo_job_application_welcome = "leo_job_application_welcome",
	leo_backlog_decline = "leo_backlog_decline",
	backlog_decline = "backlog_decline",
	leo_blind_application_welcome = "leo_blind_application_welcome",
	leo_blind_application_decline = "leo_blind_application_decline",
	leo_company_request_intro = "leo_company_request_intro",
	agent_company_request_intro = "agent_company_request_intro",
	should_send_company_intro_followup = "should_send_company_intro_followup",
	talent_accepted_company_intro = "talent_accepted_company_intro",
	talent_declined_company_intro = "talent_declined_company_intro",
	leo_request_minimal_information = "leo_request_minimal_information",
	request_minimal_information = "request_minimal_information",
	leo_assess_stuck_talent = "leo_assess_stuck_talent",
	assess_stuck_talent = "assess_stuck_talent",
	opps_questions_fup = "opps_questions_fup",
	cv_upload_fup = "cv_upload_fup",
	role_feedback_fup = "role_feedback_fup",
	interview_check_in = "interview_check_in",
	other_fup = "other_fup",
	should_ask_talent_about_withdrawal = "should_ask_talent_about_withdrawal",
	should_send_interview_invited_confirmation = "should_send_interview_invited_confirmation",
	should_send_good_luck_message = "should_send_good_luck_message",
	should_get_next_interview_scheduling = "should_get_next_interview_scheduling",
	bulk_opportunity_interest = "bulk_opportunity_interest",
	should_bulk_new_opportunities_notification = "should_bulk_new_opportunities_notification",
	screening_questions_pending = "screening_questions_pending",
	should_matchmaking_completed_notification = "should_matchmaking_completed_notification",
	should_send_referral_outreach = "should_send_referral_outreach",
	general_ping = "general_ping",
	should_request_linkedin_url = "should_request_linkedin_url",
	human_instruction = "human_instruction",
	human_instruction_completed = "human_instruction_completed",
	direct_ping = "direct_ping",
	human_reply = "human_reply",
	agent_message_sent_by_leo = "agent_message_sent_by_leo",
	agent_message_sent_by_peter = "agent_message_sent_by_peter",
	agent_message_sent = "agent_message_sent",
	agent_channel_switch = "agent_channel_switch",
	transient_failure_retry_scheduled = "transient_failure_retry_scheduled",
	profile_analyzed = "profile_analyzed",
	opportunity_declined = "opportunity_declined",
	should_send_blind_fit_nudge = "should_send_blind_fit_nudge",
}

export enum CallActivityEventType {
	calendar_call_scheduled = "calendar_call_scheduled",
	calendar_call_rescheduled = "calendar_call_rescheduled",
	calendar_call_cancelled = "calendar_call_cancelled",
	meeting_transcript_available = "meeting_transcript_available",
	phone_call_completed = "phone_call_completed",
	phone_call_missed = "phone_call_missed",
	phone_call_recording_available = "phone_call_recording_available",
	phone_call_summary_available = "phone_call_summary_available",
	phone_call_transcript_available = "phone_call_transcript_available",
	phone_call_voicemail_available = "phone_call_voicemail_available",
}

export enum TalentActivityEventType {
	first_reply_intent = "first_reply_intent",
	campaign_positive_reply = "campaign_positive_reply",
	rematch_after_interview_invited = "rematch_after_interview_invited",
	rejected_by_auto_subs = "rejected_by_auto_subs",
}

export enum NotificationType {
	email = "email",
	slack = "slack",
}

export enum MobilePlatform {
	iMessage = "iMessage",
	WhatsApp = "WhatsApp",
	SMS = "SMS",
}

export enum FitLevel {
	Strong = "strong",
	Moderate = "moderate",
	Weak = "weak",
	None = "none",
	Error = "error_eval_attempted",
	ErrorOtherRecoverable = "error_other_recoverable",
	Curated = "curated",
}

export enum Decision {
	Pass = "PASS",
	Borderline = "BORDERLINE",
	Reject = "REJECT",
}

export enum FitBucket {
	StrongFit = "STRONG_FIT",
	GoodFit = "GOOD_FIT",
	StretchFit = "STRETCH_FIT",
	Weak = "WEAK",
	NoFit = "NO_FIT",
}

export enum MatchStrength {
	StrongFit = "strong_fit",
	GoodFit = "good_fit",
	StretchFit = "stretch_fit",
}

export enum RejectionCategory {
	SeniorityMismatch = "seniority_mismatch",
	SkillsMismatch = "skills_mismatch",
	DomainMismatch = "domain_mismatch",
	RoleTypeMismatch = "role_type_mismatch",
	LocationMismatch = "location_mismatch",
	ExperienceGap = "experience_gap",
	Other = "other",
}

export enum KeyFactorSignal {
	Match = "MATCH",
	Concern = "CONCERN",
	Mismatch = "MISMATCH",
}

export type MobileChannel = (typeof MOBILE_CHANNELS)[number];
export type TalentActivityProvider = (typeof TALENT_ACTIVITY_PROVIDERS)[number];
export type ConversationChannel = (typeof CONVERSATION_CHANNELS)[number];
export type ChannelCategory = (typeof CHANNEL_CATEGORIES)[number];
export type MessageIssueSource = (typeof MESSAGE_ISSUE_SOURCES)[number];
export type LandingMedium = (typeof LANDING_MEDIUMS)[number];
export type OpportunityStatus = (typeof OPPORTUNITY_STATUSES)[number];
export type RequirementType = (typeof REQUIREMENT_TYPES)[number];
export type RequirementGroup = (typeof REQUIREMENT_GROUPS)[number];

const SLACK_MESSAGE_TYPE_VALUES: ReadonlySet<string> = new Set(Object.values(SlackMessageType));

export const isSlackMessageType = (value: string): value is SlackMessageType => SLACK_MESSAGE_TYPE_VALUES.has(value);
