export const DACH_UNIVERSITIES: string[] = [
	"ETH Zürich",
	"ETH Zurich",
	"EPFL",
	"École polytechnique fédérale de Lausanne",
	"Universität St. Gallen",
	"University of St. Gallen",
	"HSG",
	"IMD Business School",
	"IMD",
	"Universität Zürich",
	"University of Zurich",
	"Université de Genève",
	"University of Geneva",
	"Université de Lausanne",
	"University of Lausanne",
	"Universität Basel",
	"University of Basel",
	"Universität Bern",
	"University of Bern",
	"Università della Svizzera italiana",
	"USI Lugano",
	"ZHAW",

	"Universität Mannheim",
	"University of Mannheim",
	"Mannheim Business School",
	"WHU – Otto Beisheim School of Management",
	"WHU - Otto Beisheim School of Management",
	"WHU",
	"ESMT Berlin",
	"ESMT",
	"Frankfurt School of Finance & Management",
	"Frankfurt School of Finance and Management",
	"Frankfurt School",
	"HHL Leipzig Graduate School of Management",
	"HHL",
	"EBS Universität für Wirtschaft und Recht",
	"EBS Universität",
	"Hertie School",
	"Bucerius Law School",
	"Zeppelin Universität",
	"Universität Witten/Herdecke",
	"Constructor University",
	"Jacobs University Bremen",

	"Ludwig-Maximilians-Universität München",
	"LMU Munich",
	"LMU",
	"Technische Universität München",
	"TU München",
	"TUM",
	"Universität zu Köln",
	"University of Cologne",
	"Goethe-Universität Frankfurt",
	"Goethe University Frankfurt",
	"Humboldt-Universität zu Berlin",
	"Humboldt University of Berlin",
	"Freie Universität Berlin",
	"Free University of Berlin",
	"FU Berlin",
	"Technische Universität Berlin",
	"TU Berlin",
	"RWTH Aachen University",
	"RWTH Aachen",
	"Karlsruhe Institute of Technology",
	"KIT",
	"Ruprecht-Karls-Universität Heidelberg",
	"Heidelberg University",
	"Universität Heidelberg",
	"Universität Hamburg",
	"University of Hamburg",
	"Technische Universität Hamburg",
	"TU Hamburg",
	"TU Darmstadt",
	"Technische Universität Darmstadt",
	"TU Dresden",
	"Technische Universität Dresden",
	"Universität Bonn",
	"University of Bonn",
	"Westfälische Wilhelms-Universität Münster",
	"Universität Münster",
	"University of Münster",
	"WWU Münster",
	"Eberhard Karls Universität Tübingen",
	"University of Tübingen",
	"Universität Tübingen",
	"Universität Stuttgart",
	"University of Stuttgart",
	"Friedrich-Alexander-Universität Erlangen-Nürnberg",
	"FAU Erlangen-Nürnberg",
	"FAU",
	"Universität Würzburg",
	"University of Würzburg",
	"Georg-August-Universität Göttingen",
	"University of Göttingen",
	"Universität Göttingen",
	"Universität Leipzig",
	"University of Leipzig",
	"Universität Düsseldorf",
	"Heinrich Heine University Düsseldorf",
	"Universität Bayreuth",
	"University of Bayreuth",
	"Universität Regensburg",
	"University of Regensburg",
	"Universität Konstanz",
	"University of Konstanz",
	"Universität des Saarlandes",
	"Saarland University",

	"Wirtschaftsuniversität Wien",
	"WU Wien",
	"Vienna University of Economics and Business",
	"Universität Wien",
	"University of Vienna",
	"Technische Universität Wien",
	"TU Wien",
	"Vienna University of Technology",
	"Johannes Kepler Universität Linz",
	"JKU Linz",
	"Karl-Franzens-Universität Graz",
	"University of Graz",
	"Universität Innsbruck",
	"University of Innsbruck",
	"Institute of Science and Technology Austria",
	"ISTA",
	"IST Austria",
];
