export const EUROPE_UNIVERSITIES: string[] = [
	"University of Oxford",
	"Oxford",
	"Saïd Business School",
	"Said Business School",
	"University of Cambridge",
	"Cambridge",
	"Cambridge Judge Business School",
	"Judge Business School",
	"Imperial College London",
	"Imperial",
	"Imperial College Business School",
	"London School of Economics",
	"London School of Economics and Political Science",
	"LSE",
	"London Business School",
	"LBS",
	"University College London",
	"UCL",
	"King's College London",
	"KCL",

	"ETH Zürich",
	"ETH Zurich",
	"EPFL",
	"École polytechnique fédérale de Lausanne",

	"INSEAD",
	"HEC Paris",
	"École Polytechnique",
	"Ecole Polytechnique",
	"Polytechnique",
	"Sciences Po",
	"Sciences Po Paris",

	"Bocconi University",
	"SDA Bocconi",
	"Bocconi",

	"IE Business School",
	"IE University",
	"IESE Business School",
	"ESADE Business School",
	"ESADE",

	"Universität St. Gallen",
	"University of St. Gallen",
	"HSG",
	"IMD Business School",
	"IMD",
	"Universität Mannheim",
	"University of Mannheim",
	"Mannheim Business School",
	"ESMT Berlin",
	"ESMT",
	"WHU – Otto Beisheim School of Management",
	"WHU - Otto Beisheim School of Management",
	"WHU",
	"Frankfurt School of Finance & Management",
	"Frankfurt School of Finance and Management",
	"Frankfurt School",
	"HHL Leipzig Graduate School of Management",
	"HHL",
	"Ludwig-Maximilians-Universität München",
	"LMU Munich",
	"LMU",
	"Technische Universität München",
	"TU München",
	"TUM",
	"RWTH Aachen University",
	"RWTH Aachen",
	"Karlsruhe Institute of Technology",
	"KIT",
	"Universität zu Köln",
	"University of Cologne",
	"Goethe-Universität Frankfurt",
	"Goethe University Frankfurt",
	"Humboldt-Universität zu Berlin",
	"Humboldt University of Berlin",
	"Freie Universität Berlin",
	"Free University of Berlin",
	"FU Berlin",
	"Technische Universität Berlin",
	"TU Berlin",
	"Wirtschaftsuniversität Wien",
	"WU Wien",
	"Vienna University of Economics and Business",
	"Universität Wien",
	"University of Vienna",
	"Technische Universität Wien",
	"TU Wien",
	"Universität Heidelberg",
	"Heidelberg University",
	"Universität Hamburg",
	"University of Hamburg",
	"Universität Bonn",
	"University of Bonn",
	"Universität Münster",
	"University of Münster",
	"Eberhard Karls Universität Tübingen",
	"Universität Tübingen",
	"University of Tübingen",
	"FAU Erlangen-Nürnberg",
	"Friedrich-Alexander-Universität Erlangen-Nürnberg",
	"TU Darmstadt",
	"TU Dresden",
	"Universität Stuttgart",
	"Universität Zürich",
	"University of Zurich",
	"Universität Basel",
	"University of Basel",
	"Université de Genève",
	"University of Geneva",
	"Universität Bern",
	"University of Bern",
	"Hertie School",
	"Bucerius Law School",
	"Universität des Saarlandes",
	"Saarland University",
	"EBS Universität für Wirtschaft und Recht",
	"EBS Universität",
	"Constructor University",
	"Jacobs University Bremen",
	"Johannes Kepler Universität Linz",
	"JKU Linz",
	"Universität Innsbruck",
	"University of Innsbruck",

	"University of Warwick",
	"Warwick Business School",
	"University of Manchester",
	"Alliance Manchester Business School",
	"University of Edinburgh",
	"Edinburgh Business School",
	"University of Bristol",
	"University of Glasgow",
	"University of Birmingham",
	"University of Leeds",
	"University of Nottingham",
	"University of Sheffield",
	"Durham University",
	"University of St Andrews",
	"University of Bath",
	"Lancaster University",
	"University of Southampton",
	"Queen Mary University of London",
	"Cranfield School of Management",
	"Bayes Business School",
	"Cass Business School",
	"University of Liverpool",
	"University of Exeter",
	"University of York",

	"Trinity College Dublin",
	"University College Dublin",
	"UCD Michael Smurfit Graduate Business School",
	"UCD Smurfit",
	"Dublin City University",

	"ESSEC Business School",
	"ESSEC",
	"ESCP Business School",
	"ESCP",
	"EDHEC Business School",
	"emlyon business school",
	"EM Lyon",
	"Université PSL",
	"PSL",
	"Sorbonne Université",
	"Sorbonne University",
	"Institut Polytechnique de Paris",
	"Université Paris-Saclay",
	"École Normale Supérieure",
	"ENS Paris",
	"CentraleSupélec",
	"Mines Paris",
	"Mines ParisTech",
	"MINES Paris – PSL",
	"Audencia Business School",
	"SKEMA Business School",
	"Grenoble École de Management",
	"IÉSEG School of Management",
	"Toulouse Business School",
	"Université Paris-Dauphine",

	"LUISS Guido Carli",
	"Politecnico di Milano",
	"MIP Politecnico di Milano",
	"Università Cattolica del Sacro Cuore",
	"Sapienza Università di Roma",
	"Sapienza University of Rome",
	"Università di Bologna",
	"University of Bologna",
	"Politecnico di Torino",
	"Università di Padova",
	"University of Padua",
	"Scuola Normale Superiore",
	"Scuola Superiore Sant'Anna",
	"Università di Trento",

	"Universitat Pompeu Fabra",
	"Universidad Carlos III de Madrid",
	"Universidad Autónoma de Madrid",
	"Universidad Complutense de Madrid",
	"Universidad de Barcelona",
	"Universitat de Barcelona",
	"Universidad Politécnica de Madrid",
	"Universitat Politècnica de Catalunya",
	"Universidad Pontificia Comillas",
	"ICADE",
	"Universidad de Navarra",
	"University of Navarra",
	"EADA Business School",

	"Nova School of Business and Economics",
	"Nova SBE",
	"Católica Lisbon School of Business and Economics",
	"Católica Lisbon",
	"Catolica Lisbon",
	"Universidade do Porto",
	"University of Porto",
	"Porto Business School",
	"ISCTE Business School",
	"Universidade de Lisboa",
	"University of Lisbon",
	"Instituto Superior Técnico",

	"Erasmus University Rotterdam",
	"Rotterdam School of Management",
	"RSM",
	"University of Amsterdam",
	"Amsterdam Business School",
	"UvA",
	"Vrije Universiteit Amsterdam",
	"VU Amsterdam",
	"Delft University of Technology",
	"TU Delft",
	"Eindhoven University of Technology",
	"TU/e",
	"TU Eindhoven",
	"Wageningen University & Research",
	"Wageningen University",
	"Tilburg University",
	"Maastricht University",
	"Leiden University",
	"Utrecht University",
	"University of Groningen",
	"Nyenrode Business University",

	"KU Leuven",
	"Catholic University of Leuven",
	"Université libre de Bruxelles",
	"ULB",
	"Solvay Brussels School",
	"Solvay Brussels School of Economics and Management",
	"UCLouvain",
	"Université catholique de Louvain",
	"Vlerick Business School",
	"Ghent University",
	"University of Antwerp",
	"Antwerp Management School",

	"Stockholm School of Economics",
	"SSE",
	"KTH Royal Institute of Technology",
	"KTH",
	"Karolinska Institutet",
	"Lund University",
	"Uppsala University",
	"Chalmers University of Technology",
	"Stockholm University",
	"University of Gothenburg",

	"Copenhagen Business School",
	"CBS",
	"University of Copenhagen",
	"Technical University of Denmark",
	"DTU",
	"Aarhus University",

	"Aalto University",
	"University of Helsinki",
	"Hanken School of Economics",

	"BI Norwegian Business School",
	"NHH Norwegian School of Economics",
	"Norwegian University of Science and Technology",
	"NTNU",
	"University of Oslo",

	"University of Iceland",

	"Central European University",
	"CEU",
	"Charles University",
	"Charles University Prague",
	"Warsaw School of Economics",
	"SGH Warsaw School of Economics",
	"University of Warsaw",
	"Kozminski University",
	"University of Ljubljana",
	"University of Zagreb",
	"Comenius University Bratislava",

	"Athens University of Economics and Business",
	"National and Kapodistrian University of Athens",
	"University of Athens",

	"Boğaziçi University",
	"Bogazici University",
	"Koç University",
	"Koc University",
	"Sabancı University",
	"Sabanci University",
	"Bilkent University",
	"Middle East Technical University",
	"METU",
];
