export type HeaderWire = {
  id: string;
  firstname: string | null;
  lastname: string | null;
  email: string | null;
  phone: string | null;
  linkedinUrl: string | null;
  avatarUrl: string | null;
  eloScore: number | null;
  openForOpportunities: boolean | null;
  openForOpportunitiesLastChange: string | null;
  owner: string | null;
  nanoId: string | null;
  userId: string | null;
  source: string | null;
  occupation: string | null;
  location: string | null;
  status: string | null;
  priorityStar: boolean | null;
  followUpDate: string | null;
  followUpNote: string | null;
  availableStartDate: string | null;
  visaSponsorshipNeeded: boolean | null;
  yearsExperience: number | null;
  jobSearchStatus: string | null;
  allowDirectSubmission: boolean | null;
  inboundMessageCount: number | null;
  outboundMessageCount: number | null;
  answered: boolean | null;
  agentMemory: Array<{ key: string; value: string; updatedAt: string }>;
  createdAt: string;
  rating: number | null;
  resumePath: string | null;
  linkedinUrn: string | null;
  linkedinConnections: number | null;
  linkedinFollowers: number | null;
  utmParameter: string | null;
  recruiterId: string | null;
  portfolioUrl: string | null;
  githubUrl: string | null;
  xUrl: string | null;
  otherLinks: Array<{ type: string; address: string }>;
  badgeCounts: { opportunities: number; communications: number };
};

type Wire = Record<string, any>;

export declare function headerWire(...args: unknown[]): HeaderWire;
export declare function fitReasonWire(...args: unknown[]): Wire;
export declare function opportunityCountsWire(...args: unknown[]): Wire;
export declare function responseTimeWire(...args: unknown[]): Wire;
export declare function unifiedTextWire(...args: unknown[]): Wire;
