export const PERSONAL_EMAIL_DOMAINS = [
	"gmail.com",
	"googlemail.com",
	"yahoo.com",
	"yahoo.co.uk",
	"yahoo.ca",
	"yahoo.co.jp",
	"yahoo.com.ae",
	"yahoo.com.ar",
	"yahoo.com.au",
	"yahoo.com.bd",
	"yahoo.com.br",
	"yahoo.com.eg",
	"yahoo.com.hk",
	"yahoo.com.id",
	"yahoo.com.kh",
	"yahoo.com.la",
	"yahoo.com.lk",
	"yahoo.com.mm",
	"yahoo.com.mx",
	"yahoo.com.my",
	"yahoo.com.np",
	"yahoo.com.ph",
	"yahoo.com.pk",
	"yahoo.com.sa",
	"yahoo.com.sg",
	"yahoo.com.th",
	"yahoo.com.tr",
	"yahoo.com.tw",
	"yahoo.com.vn",
	"yahoo.de",
	"yahoo.es",
	"yahoo.fr",
	"yahoo.in",
	"yahoo.it",
	"ymail.com",
	"hotmail.com",
	"hotmail.co.uk",
	"hotmail.de",
	"hotmail.fr",
	"hotmail.es",
	"hotmail.it",
	"hotmail.com.br",
	"outlook.com",
	"outlook.co.uk",
	"outlook.de",
	"outlook.fr",
	"outlook.es",
	"outlook.it",
	"outlook.com.br",
	"outlook.in",
	"live.com",
	"live.co.uk",
	"live.de",
	"live.fr",
	"live.nl",
	"msn.com",
	"web.de",
	"gmx.de",
	"gmx.at",
	"gmx.ch",
	"t-online.de",
	"freenet.de",
	"orange.fr",
	"wanadoo.fr",
	"laposte.net",
	"free.fr",
	"libero.it",
	"mail.ru",
	"yandex.ru",
	"seznam.cz",
	"wp.pl",
	"rediffmail.com",
	"qq.com",
	"163.com",
	"126.com",
	"naver.com",
	"daum.net",
	"icloud.com",
	"me.com",
	"mac.com",
	"aol.com",
	"protonmail.com",
	"proton.me",
	"zoho.com",
	"yandex.com",
	"mail.com",
	"gmx.com",
	"gmx.net",
	"posteo.de",
	"fastmail.com",
	"tutanota.com",
] as const;

export function extractEmailDomain(email: string): string | null {
	const parts = email.split("@");
	if (parts.length !== 2) return null;
	const domain = parts[1].toLowerCase().trim();
	return domain || null;
}

const PERSONAL_EMAIL_DOMAIN_SET = new Set<string>(PERSONAL_EMAIL_DOMAINS);

const PROBE_RESISTANT_EMAIL_DOMAINS = new Set<string>([
	"yahoo.com",
	"ymail.com",
	"yahoo.co.uk",
	"yahoo.fr",
	"yahoo.de",
	"yahoo.co.in",
	"yahoo.ca",
	"yahoo.com.au",
	"yahoo.co.jp",
	"rocketmail.com",
	"aol.com",
	"aim.com",
	"netscape.net",
	"cs.com",
	"compuserve.com",
	"hotmail.com",
	"live.com",
	"msn.com",
	"outlook.com",
	"icloud.com",
	"me.com",
	"mac.com",
	"att.net",
	"bellsouth.net",
	"pacbell.net",
	"ameritech.net",
	"swbell.net",
	"prodigy.net",
	"snet.net",
	"flash.net",
	"nvbell.net",
	"comcast.net",
	"sbcglobal.net",
	"verizon.net",
	"earthlink.net",
	"juno.com",
	"netzero.net",
	"windstream.net",
	"centurylink.net",
	"centurytel.net",
	"embarqmail.com",
	"frontier.com",
	"frontiernet.net",
	"roadrunner.com",
	"rr.com",
	"twc.com",
	"optonline.net",
	"optimum.net",
	"cox.net",
	"charter.net",
	"mindspring.com",
	"webtv.net",
	"discover.com",
	"accenture.com",
]);

export function isPersonalEmailDomain(domain: string): boolean {
	return PERSONAL_EMAIL_DOMAIN_SET.has(domain.toLowerCase());
}

export function isProbeResistantEmail(email: string): boolean {
	const domain = extractEmailDomain(email);
	if (!domain) return false;
	return (
		PROBE_RESISTANT_EMAIL_DOMAINS.has(domain) ||
		domain.endsWith(".edu") ||
		domain.endsWith(".edu.tw") ||
		domain.endsWith(".ac.uk")
	);
}
