import { DACH_UNIVERSITIES, EUROPE_UNIVERSITIES } from "./top-universities-eu/index.ts";

export type RoleCluster =
	| "engineering"
	| "business"
	| "sales"
	| "marketing"
	| "finance"
	| "legal"
	| "recruiting"
	| "design"
	| "data_science"
	| "product"
	| "general";

const ENGINEERING_UNIVERSITIES: string[] = [
	"Massachusetts Institute of Technology",
	"MIT",
	"Stanford University",
	"Carnegie Mellon University",
	"CMU",
	"University of California, Berkeley",
	"UC Berkeley",
	"California Institute of Technology",
	"Caltech",
	"Georgia Institute of Technology",
	"Georgia Tech",
	"University of Illinois Urbana-Champaign",
	"UIUC",
	"University of Washington",
	"Cornell University",
	"Princeton University",
	"University of Michigan",
	"University of Texas at Austin",
	"UT Austin",
	"University of California, Los Angeles",
	"UCLA",
	"Columbia University",
	"University of Wisconsin-Madison",
	"University of California, San Diego",
	"UCSD",
	"Purdue University",
	"University of Maryland",
	"Harvard University",
	"Yale University",
	"University of Pennsylvania",
	"Brown University",
	"Duke University",
	"Northwestern University",
	"Rice University",
	"University of Southern California",
	"USC",
	"University of Massachusetts Amherst",
	"UMass Amherst",
	"Northeastern University",
	"Virginia Tech",
	"University of Colorado Boulder",
	"University of Minnesota",
	"Ohio State University",
	"Penn State University",
	"Arizona State University",
	"ASU",

	"University of Oxford",
	"Oxford",
	"University of Cambridge",
	"Cambridge",
	"Imperial College London",
	"Imperial",
	"University College London",
	"UCL",
	"University of Edinburgh",
	"University of Manchester",

	"ETH Zurich",
	"EPFL",
	"Technical University of Munich",
	"TUM",
	"RWTH Aachen University",
	"Delft University of Technology",
	"TU Delft",
	"KTH Royal Institute of Technology",

	"University of Toronto",
	"University of Waterloo",
	"Waterloo",
	"University of British Columbia",
	"UBC",
	"McGill University",
	"McMaster University",
	"Queen's University",
	"Western University",
	"University of Alberta",
	"University of Montreal",
	"Université de Montréal",
	"Polytechnique Montréal",
	"Polytechnique Montreal",
	"École de technologie supérieure",
	"ETS Montréal",
	"Simon Fraser University",
	"University of Calgary",
	"University of Ottawa",
	"Concordia University",
	"University of Victoria",

	"National University of Singapore",
	"NUS",
	"Nanyang Technological University",
	"NTU Singapore",
	"Tsinghua University",
	"Peking University",
	"University of Tokyo",
	"KAIST",
	"Hong Kong University of Science and Technology",
	"HKUST",
	"Indian Institute of Technology",
	"IIT",
	"IIT Bombay",
	"IIT Delhi",
	"IIT Madras",
	"IIT Kanpur",

	"Technion - Israel Institute of Technology",
	"Technion",
	"Tel Aviv University",

	"University of Melbourne",
	"University of Sydney",
	"Monash University",
	"University of New South Wales",
	"UNSW",
	"Australian National University",
	"ANU",

	"Seoul National University",
	"SNU",
	"Yonsei University",
	"Korea University",

	"Kyoto University",
	"Keio University",
	"Waseda University",

	"Université PSL",
	"Université Paris-Saclay",
	"Sorbonne University",
	"Institut Polytechnique de Paris",

	"Ludwig-Maximilians-Universität München",
	"LMU Munich",
	"Universität Heidelberg",
	"Karlsruhe Institute of Technology",
	"KIT",

	"University of Zurich",

	"KU Leuven",
	"University of Amsterdam",
	"University of Copenhagen",
	"Lund University",
	"University of Bristol",
	"University of Glasgow",
	"University of Birmingham",
	"Trinity College Dublin",

	"Chinese University of Hong Kong",
	"CUHK",
	"City University of Hong Kong",
	"Hong Kong Polytechnic University",

	"Fudan University",
	"Zhejiang University",
	"Shanghai Jiao Tong University",

	"University of Alberta",

	"Johns Hopkins University",

	"University of Auckland",
];

const BUSINESS_UNIVERSITIES: string[] = [
	"Harvard Business School",
	"Harvard University",
	"Stanford Graduate School of Business",
	"Stanford University",
	"Wharton School",
	"University of Pennsylvania",
	"Penn",
	"Kellogg School of Management",
	"Northwestern University",
	"Booth School of Business",
	"University of Chicago",
	"MIT Sloan",
	"Massachusetts Institute of Technology",
	"MIT",
	"Columbia Business School",
	"Columbia University",
	"Haas School of Business",
	"University of California, Berkeley",
	"UC Berkeley",
	"Tuck School of Business",
	"Dartmouth College",
	"Yale School of Management",
	"Yale University",
	"Ross School of Business",
	"University of Michigan",
	"Fuqua School of Business",
	"Duke University",
	"Anderson School of Management",
	"University of California, Los Angeles",
	"UCLA",
	"Stern School of Business",
	"New York University",
	"NYU",
	"McCombs School of Business",
	"University of Texas at Austin",
	"UT Austin",
	"Tepper School of Business",
	"Carnegie Mellon University",
	"CMU",
	"Darden School of Business",
	"University of Virginia",
	"Johnson Graduate School of Management",
	"Cornell University",
	"Goizueta Business School",
	"Emory University",
	"Kelley School of Business",
	"Indiana University",
	"Marshall School of Business",
	"University of Southern California",
	"USC",

	"Rotman School of Management",
	"University of Toronto",
	"Ivey Business School",
	"Western University",
	"Schulich School of Business",
	"York University",
	"Desautels Faculty of Management",
	"McGill University",
	"Sauder School of Business",
	"University of British Columbia",
	"UBC",
	"Smith School of Business at Queen's University",
	"Smith School of Business",
	"Queen's University",
	"HEC Montréal",
	"HEC Montreal",
	"Université de Montréal",
	"University of Montreal",
	"DeGroote School of Business",
	"McMaster University",
	"Telfer School of Management",
	"University of Ottawa",
	"Alberta School of Business",
	"University of Alberta",

	"London Business School",
	"LBS",
	"Oxford Said Business School",
	"University of Oxford",
	"Cambridge Judge Business School",
	"University of Cambridge",
	"London School of Economics",
	"LSE",
	"Imperial College Business School",
	"Imperial College London",
	"Warwick Business School",
	"University of Warwick",

	"INSEAD",
	"HEC Paris",
	"IE Business School",
	"IESE Business School",
	"ESADE",
	"SDA Bocconi",
	"Bocconi University",
	"Rotterdam School of Management",
	"IMD",

	"National University of Singapore",
	"NUS",
	"CEIBS",
	"Hong Kong University",
	"HKU",
	"Singapore Management University",
	"SMU",

	"Copenhagen Business School",
	"CBS",
	"Mannheim Business School",
	"ESMT Berlin",
	"ESMT",
	"ESCP Business School",
	"ESCP",
	"ESSEC Business School",
	"ESSEC",
	"University of St. Gallen",
	"St. Gallen",
	"Stockholm School of Economics",

	"University of Sydney Business School",
	"Melbourne Business School",
	"Monash Business School",

	"Indian Institute of Management Ahmedabad",
	"IIM Ahmedabad",
	"Indian Institute of Management Bangalore",
	"IIM Bangalore",
	"Indian School of Business",
	"ISB",
];

const FINANCE_UNIVERSITIES: string[] = [
	"Wharton School",
	"University of Pennsylvania",
	"Penn",
	"Harvard University",
	"Stanford University",
	"University of Chicago",
	"Booth School of Business",
	"MIT",
	"Massachusetts Institute of Technology",
	"MIT Sloan",
	"Columbia University",
	"New York University",
	"NYU",
	"Stern School of Business",
	"Princeton University",
	"Yale University",
	"Cornell University",
	"Duke University",
	"University of California, Berkeley",
	"UC Berkeley",
	"Northwestern University",
	"University of Michigan",
	"Carnegie Mellon University",
	"CMU",
	"University of Texas at Austin",
	"UT Austin",
	"University of California, Los Angeles",
	"UCLA",
	"Georgetown University",

	"London School of Economics",
	"LSE",
	"University of Oxford",
	"Oxford",
	"University of Cambridge",
	"Cambridge",
	"Imperial College London",
	"University College London",
	"UCL",
	"London Business School",
	"LBS",
	"City University London",
	"Cass Business School",

	"HEC Paris",
	"ESSEC",
	"Bocconi University",
	"ETH Zurich",
	"University of St. Gallen",
	"Frankfurt School of Finance",
	"Erasmus University Rotterdam",

	"National University of Singapore",
	"NUS",
	"Hong Kong University of Science and Technology",
	"HKUST",
	"University of Hong Kong",
	"HKU",
	"Peking University",
	"Tsinghua University",
	"Seoul National University",
	"SNU",

	"University of St. Gallen",
	"Stockholm School of Economics",
	"Frankfurt School of Finance",
	"Mannheim Business School",

	"University of Melbourne",
	"University of Sydney",
];

const LEGAL_UNIVERSITIES: string[] = [
	"Yale Law School",
	"Yale University",
	"Harvard Law School",
	"Harvard University",
	"Stanford Law School",
	"Stanford University",
	"Columbia Law School",
	"Columbia University",
	"University of Chicago Law School",
	"University of Chicago",
	"New York University School of Law",
	"NYU",
	"University of Pennsylvania Law School",
	"Penn Law",
	"University of Virginia School of Law",
	"University of Virginia",
	"University of California, Berkeley School of Law",
	"Berkeley Law",
	"UC Berkeley",
	"University of Michigan Law School",
	"University of Michigan",
	"Duke Law School",
	"Duke University",
	"Northwestern Pritzker School of Law",
	"Northwestern University",
	"Cornell Law School",
	"Cornell University",
	"Georgetown University Law Center",
	"Georgetown University",
	"University of Texas School of Law",
	"UT Austin",
	"UCLA School of Law",
	"University of California, Los Angeles",
	"UCLA",
	"Vanderbilt Law School",
	"Vanderbilt University",
	"Washington University in St. Louis School of Law",
	"WashU",
	"University of Southern California Gould School of Law",
	"USC",
	"Boston University School of Law",
	"Boston University",
	"University of Minnesota Law School",
	"University of Notre Dame Law School",
	"University of Notre Dame",

	"University of Oxford",
	"Oxford",
	"University of Cambridge",
	"Cambridge",
	"London School of Economics",
	"LSE",
	"University College London",
	"UCL",
	"King's College London",

	"University of Amsterdam",
	"Leiden University",
	"Sciences Po",
	"Humboldt University of Berlin",
	"Sorbonne University",
	"Université PSL",
	"LMU Munich",
	"Trinity College Dublin",

	"National University of Singapore",
	"NUS",
	"University of Melbourne",
	"University of Sydney",
	"University of Hong Kong",
	"HKU",
];

const DESIGN_UNIVERSITIES: string[] = [
	"Rhode Island School of Design",
	"RISD",
	"Parsons School of Design",
	"Parsons",
	"Stanford University",
	"d.school",
	"Carnegie Mellon University",
	"CMU",
	"MIT",
	"Massachusetts Institute of Technology",
	"Media Lab",
	"Pratt Institute",
	"School of Visual Arts",
	"SVA",
	"ArtCenter College of Design",
	"California College of the Arts",
	"CCA",
	"Savannah College of Art and Design",
	"SCAD",
	"California Institute of the Arts",
	"CalArts",
	"Cooper Union",
	"University of Cincinnati",
	"Illinois Institute of Technology",
	"IIT",
	"Georgia Tech",
	"Georgia Institute of Technology",
	"University of Washington",
	"University of Michigan",
	"Indiana University",

	"Royal College of Art",
	"RCA",
	"Central Saint Martins",
	"Goldsmiths University of London",
	"University of the Arts London",
	"UAL",
	"Glasgow School of Art",

	"Delft University of Technology",
	"TU Delft",
	"Aalto University",
	"Umeå University",
	"Design Academy Eindhoven",
	"Politecnico di Milano",

	"National University of Singapore",
	"NUS",
	"Hong Kong Polytechnic University",
];

const DATA_SCIENCE_UNIVERSITIES: string[] = [
	"Stanford University",
	"Massachusetts Institute of Technology",
	"MIT",
	"University of California, Berkeley",
	"UC Berkeley",
	"Carnegie Mellon University",
	"CMU",
	"Harvard University",
	"University of Washington",
	"Columbia University",
	"University of Michigan",
	"Georgia Institute of Technology",
	"Georgia Tech",
	"University of Illinois at Urbana-Champaign",
	"UIUC",
	"Cornell University",
	"Princeton University",
	"California Institute of Technology",
	"Caltech",
	"University of Chicago",
	"Duke University",
	"New York University",
	"NYU",

	"University of Toronto",
	"ETH Zurich",
	"EPFL",
	"University of Oxford",
	"University of Cambridge",
	"Imperial College London",
	"University of Edinburgh",
	"National University of Singapore",
	"NUS",
	"Tsinghua University",
	"Peking University",
	"University of Melbourne",
	"Seoul National University",
	"Université Paris-Saclay",
	"Technical University of Munich",
	"TUM",
];

const RECRUITING_UNIVERSITIES: string[] = [
	"Cornell University",
	"Cornell ILR School",
	"University of Michigan",
	"University of Minnesota",
	"Michigan State University",
	"Rutgers University",
	"University of Illinois Urbana-Champaign",
	"UIUC",
	"Penn State University",
	"University of South Carolina",
	"Ohio State University",
	"Purdue University",
	"University of Georgia",
	"University of Maryland",
	"University of Iowa",
	"George Washington University",
	"University of Wisconsin-Madison",
	"Indiana University",
	"Northwestern University",
	"MIT",
	"Massachusetts Institute of Technology",
	"Stanford University",
	"Harvard University",
	"University of Pennsylvania",
	"Wharton School",
	"Columbia University",
	"New York University",
	"NYU",
	"University of Southern California",
	"USC",
	"University of Texas at Austin",
	"UT Austin",
	"Vanderbilt University",
	"Georgetown University",
	"University of North Carolina at Chapel Hill",
	"Boston University",
	"University of California, Berkeley",
	"UC Berkeley",

	"London School of Economics",
	"LSE",
	"University of Oxford",
	"Oxford",
	"University of Cambridge",
	"Cambridge",
	"King's College London",
	"University of Manchester",
	"University of Warwick",

	"Erasmus University Rotterdam",
	"University of Amsterdam",
	"INSEAD",

	"University of Toronto",
	"National University of Singapore",
	"NUS",
	"Hong Kong University",
	"HKU",
];

const PRODUCT_UNIVERSITIES: string[] = [
	"Stanford University",
	"MIT",
	"Harvard University",
	"Carnegie Mellon University",
	"University of California, Berkeley",
	"University of Pennsylvania",
	"Northwestern University",
	"University of Michigan",
	"Columbia University",
	"Cornell University",
	"University of Washington",
	"Georgia Institute of Technology",
	"Duke University",
	"New York University",
	"University of Chicago",
	"University of Texas at Austin",
	"University of Virginia",
	"Yale University",
	"Princeton University",
	"University of Illinois at Urbana-Champaign",
];

const GENERAL_UNIVERSITIES: string[] = [
	"Stanford University",
	"Harvard University",
	"MIT",
	"Massachusetts Institute of Technology",
	"University of Pennsylvania",
	"Columbia University",
	"Yale University",
	"Princeton University",
	"University of Chicago",
	"Duke University",
	"Northwestern University",
	"Cornell University",
	"University of California, Berkeley",
	"UC Berkeley",
	"University of Michigan",
	"New York University",
	"NYU",
	"Carnegie Mellon University",
	"CMU",
	"University of Virginia",
	"Georgetown University",
	"University of Texas at Austin",
	"UT Austin",
	"University of Southern California",
	"USC",
	"University of California, Los Angeles",
	"UCLA",
	"University of Washington",
	"Georgia Institute of Technology",
	"Georgia Tech",
	"University of North Carolina at Chapel Hill",
	"Emory University",
	"Vanderbilt University",
	"Johns Hopkins University",
	"Brown University",
	"Dartmouth College",
	"Rice University",
	"University of Illinois Urbana-Champaign",
	"UIUC",
	"University of California, San Diego",
	"UCSD",

	"University of Oxford",
	"Oxford",
	"University of Cambridge",
	"Cambridge",
	"Imperial College London",
	"London School of Economics",
	"LSE",
	"University College London",
	"UCL",
	"University of Edinburgh",
	"University of Manchester",
	"University of Warwick",
	"University of Bristol",
	"University of Glasgow",
	"University of Birmingham",

	"ETH Zurich",
	"EPFL",
	"Technical University of Munich",
	"TUM",
	"LMU Munich",
	"Universität Heidelberg",
	"KU Leuven",
	"University of Amsterdam",
	"Delft University of Technology",
	"TU Delft",
	"University of Copenhagen",
	"Lund University",
	"KTH Royal Institute of Technology",
	"Université PSL",
	"Sorbonne University",
	"Trinity College Dublin",

	"University of Toronto",
	"University of Waterloo",
	"University of British Columbia",
	"UBC",
	"McGill University",

	"University of Melbourne",
	"University of Sydney",
	"Monash University",
	"University of New South Wales",
	"UNSW",
	"Australian National University",
	"ANU",

	"National University of Singapore",
	"NUS",
	"Nanyang Technological University",
	"NTU Singapore",
	"Tsinghua University",
	"Peking University",
	"University of Tokyo",
	"Seoul National University",
	"SNU",
	"Hong Kong University of Science and Technology",
	"HKUST",
	"University of Hong Kong",
	"HKU",

	"Technion",
	"Tel Aviv University",

	"University of Auckland",
];

const UNIVERSITIES_BY_CLUSTER: Record<RoleCluster, string[]> = {
	engineering: ENGINEERING_UNIVERSITIES,
	business: BUSINESS_UNIVERSITIES,
	sales: BUSINESS_UNIVERSITIES,
	marketing: BUSINESS_UNIVERSITIES,
	finance: FINANCE_UNIVERSITIES,
	legal: LEGAL_UNIVERSITIES,
	recruiting: RECRUITING_UNIVERSITIES,
	design: DESIGN_UNIVERSITIES,
	data_science: DATA_SCIENCE_UNIVERSITIES,
	product: PRODUCT_UNIVERSITIES,
	general: GENERAL_UNIVERSITIES,
};

export type Region = "dach" | "europe" | "na";

export function getUniversitiesForCluster(cluster: RoleCluster, region?: Region): string[] {
	if (region === "dach") return DACH_UNIVERSITIES;
	if (region === "europe") return EUROPE_UNIVERSITIES;
	return UNIVERSITIES_BY_CLUSTER[cluster] || GENERAL_UNIVERSITIES;
}
